
---
- hosts: "{{ my_host }}"
  vars:
    virtualenv_path: "~"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
      become: yes

    - name: Install a list of packages
      apt:
        pkg:
        - build-essential 
        - libssl-dev 
        - libffi-dev 
        - python3.6-dev 
        - python-pip 
        - libsasl2-dev 
        - libldap2-dev
        - python3-venv
        force_apt_get: yes
        state: present
      become: yes
    
    - name: activate virtualenv
      shell: "{{ item }}"
      with_items:
          - python3 -m venv {{ virtualenv_path }}/venv
          # - . {{ virtualenv_path}}/venv/bin/activate
    
    - name: install the package, force upgrade
      pip: 
        name: setuptools, pip
        virtualenv: {{ virtualenv_path }}/venv
        extra_args: --upgrade

    - name: install superset 
      pip:
        name: apache-superset
        virtualenv: {{ virtualenv_path }}/venv
        state: present

    - shell: {{ virtualenv_path }}/venv/bin/superset {{ item }}
      with_items:
        - db upgrade
        - load_examples
        - init
        # - run -h {{ superset_host }} -p {{ superset_port }}
