
---
- hosts: "{{ my_host }}"
  vars:
    superset_host: 0.0.0.0
    superset_port: 8088
    virtualenv_path: "~"

  tasks:
    - shell: {{ virtualenv_path }}/venv/bin/superset {{ item }}
      with_items:
      - run -h {{ superset_host }} -p {{ superset_port }}
